utilisateur_homepage:
    path:     /account
    defaults: { _controller: UtilisateurBundle:Default:index }
utilisateur_profil:
    path:     /profil
    defaults: { _controller: UtilisateurBundle:Default:index }

utilisateur_changement:
    path:     /profil/changer
    defaults: { _controller: UtilisateurBundle:Default:changer }