<?php

namespace Pharmacie\MedicamentBundle\Repository;

/**
 * SorteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SorteRepository extends \Doctrine\ORM\EntityRepository
{
}
